language: node_js
sudo: required
node_js:
  - 8
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_5335f12e2ec8_key -iv $encrypted_5335f12e2ec8_iv
    -in aliyun_liuxsen.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 101.200.48.138\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install -g hexo-cli
install:
  - npm install
  - npm install hexo-deployer-git --save
script:
  - hexo clean
  - hexo generate
after_script:
  - git config user.name "liuxsen"
  - git config user.email "wyliuxsen.com"
  - sed -i "s/token/${token}/g" ./_config.yml
  - hexo deploy
  - tar -zcvf blog.tar.gz ./public # 打包并压缩代码
  - ssh liuxsen@101.200.48.138 'mkdir -p /home/liuxsen/www/blog' # 新建目录
  - scp blog.tar.gz liuxsen@101.200.48.138:/home/liuxsen/www/blog/
